const SUPABASE_URL='https://pziazogdzjzrixhiqmwm.supabase.co';
const API_KEY='sb_publishable_Ybhm2asFntkh3oHPF5dIZw_V_WsL6lP';
const SESSION_KEY='augustum-tid-session';
const $=s=>document.querySelector(s);
let session=null,currentEmployee=null,employees=[],dailyReports=[],transportProposals=[],approvalData=null,monthOverview=null,payrollReport=null,hmsData={documents:[],deviations:[]},sickLeaveData={requests:[]},vacationData={requests:[],carryovers:[]},hrData={documents:[],contracts:[],employees:[]},pendingToggle=null,loginEmail='',clockState=null,scannerStream=null,scannerTimer=null;

function show(message){const el=$('#toast');el.textContent=message;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),3000)}
async function request(path,{method='GET',body,token}={}){const response=await fetch(SUPABASE_URL+path,{method,headers:{apikey:API_KEY,'Content-Type':'application/json',...(token?{Authorization:`Bearer ${token}`}:{})},body:body?JSON.stringify(body):undefined});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error_description||data.msg||data.error||'Noe gikk galt. Prøv igjen.');return data}
function saveSession(value){session=value;value?localStorage.setItem(SESSION_KEY,JSON.stringify(value)):localStorage.removeItem(SESSION_KEY)}
async function refreshSession(){if(!session?.refresh_token)return false;try{const data=await request('/auth/v1/token?grant_type=refresh_token',{method:'POST',body:{refresh_token:session.refresh_token}});saveSession(data);return true}catch{saveSession(null);return false}}
async function authenticated(path,options={}){if(!session?.access_token)throw new Error('Du må logge inn.');try{return await request(path,{...options,token:session.access_token})}catch(error){if(/jwt|token|expired/i.test(error.message)&&await refreshSession())return request(path,{...options,token:session.access_token});throw error}}
function initials(name){return name.split(/\s+/).map(x=>x[0]).slice(0,2).join('').toUpperCase()}
function roleText(role){return({employee:'Ansatt',manager:'Avdelingsleder',admin:'Admin'})[role]||role}

$('#emailForm').onsubmit=async event=>{event.preventDefault();loginEmail=$('#email').value.trim().toLowerCase();const button=event.submitter;button.disabled=true;button.textContent='Sender kode …';try{await request('/auth/v1/otp',{method:'POST',body:{email:loginEmail,create_user:false}});$('#emailForm').classList.add('hidden');$('#codeForm').classList.remove('hidden');$('#sentTo').textContent=`Koden er sendt til ${loginEmail}.`;$('#code').focus()}catch(error){show(error.message)}finally{button.disabled=false;button.textContent='Send engangskode'}};
$('#back').onclick=()=>{$('#codeForm').classList.add('hidden');$('#emailForm').classList.remove('hidden')};
$('#code').oninput=event=>{event.target.value=event.target.value.replace(/\D/g,'').slice(0,8)};
$('#codeForm').onsubmit=async event=>{event.preventDefault();const token=$('#code').value.replace(/\D/g,'');if(!/^(?:\d{6}|\d{8})$/.test(token))return show('Skriv inn hele koden på seks eller åtte sifre.');const button=event.submitter;button.disabled=true;button.textContent='Kontrollerer …';try{const data=await request('/auth/v1/verify',{method:'POST',body:{email:loginEmail,token,type:'email'}});saveSession(data);await openApp()}catch(error){show('Koden er ugyldig eller utløpt. Be om en ny kode og prøv igjen.')}finally{button.disabled=false;button.textContent='Bekreft og logg inn'}};
$('#logout').onclick=async()=>{try{await authenticated('/auth/v1/logout',{method:'POST'})}catch{}saveSession(null);location.reload()};

async function getMe(){const data=await authenticated('/rest/v1/employees?select=id,employee_number,full_name,email,phone_number,role,active&auth_user_id=eq.'+encodeURIComponent(session.user.id));return data[0]}
async function openApp(){let me;try{me=await getMe();if(!me&&session.user?.email?.toLowerCase()==='post@augustum.no'){await authenticated('/functions/v1/employee-admin',{method:'POST',body:{action:'bootstrap'}});me=await getMe()}if(!me?.active)throw new Error('Brukeren er ikke aktiv. Kontakt administrator.')}catch(error){saveSession(null);show(error.message);return}currentEmployee=me;$('#login').classList.add('hidden');$('#app').classList.remove('hidden');$('#logout').classList.remove('hidden');$('#welcome').textContent=`Hei, ${me.full_name}.`;$('#identity').textContent=`${me.employee_number} · ${me.email}`;$('#roleBadge').textContent=roleText(me.role);if(me.role==='admin'){$('#employeeHome').classList.add('hidden');$('#adminPanel').classList.remove('hidden');try{await authenticated('/functions/v1/employee-admin',{method:'POST',body:{action:'bootstrap'}});await refreshSession()}catch(error){show(error.message)}const results=await Promise.allSettled([loadEmployees(),loadDailyReports()]);const failed=results.find(result=>result.status==='rejected');if(failed)show(failed.reason?.message||'Noen admindata kunne ikke lastes inn.')}else{await loadClock();const params=new URLSearchParams(location.search),qrToken=params.get('qr');if(qrToken){params.delete('qr');const query=params.toString();history.replaceState({},'',`${location.pathname}${query?`?${query}`:''}${location.hash}`);await clockWithQr(qrToken)}}}

async function loadClock(){try{clockState=await authenticated('/functions/v1/time-clock');if(!$('#periodMonth').value)$('#periodMonth').value=localMonth();renderClock();renderQrStatus()}catch(error){show(error.message);$('#clockStatus').textContent='Kunne ikke hente status'}}
function renderQrStatus(){if(!$('#qrStatusText'))return;const qr=clockState?.qr_status;if(!qr){$('#qrStatusText').textContent='Ingen aktiv QR-kode';$('#qrStatusDetail').textContent='Lag en ny kode før de ansatte kan stemple med QR.';$('#revokeQr').classList.add('hidden');return}$('#qrStatusText').textContent='Aktiv QR-kode';const mode=qr.location_check_required?'100-meterskontroll er aktiv.':'Testversjon: posisjonsgrensen er deaktivert.';$('#qrStatusDetail').textContent=`${mode} Gyldig til ${new Date(qr.expires_at).toLocaleDateString('nb-NO')}.`;$('#revokeQr').classList.remove('hidden')}
function formatTime(value){return new Date(value).toLocaleTimeString('nb-NO',{timeZone:'Europe/Oslo',hour:'2-digit',minute:'2-digit'})}
function formatDay(value){return new Date(value).toLocaleDateString('nb-NO',{timeZone:'Europe/Oslo',weekday:'long',day:'2-digit',month:'2-digit'})}
function durationHours(entry){return entry.ended_at?Math.max(0,(new Date(entry.ended_at)-new Date(entry.started_at))/3600000):0}
function localMonth(){return new Intl.DateTimeFormat('sv-SE',{timeZone:'Europe/Oslo',year:'numeric',month:'2-digit'}).format(new Date()).slice(0,7)}
function osloMonth(value){return new Intl.DateTimeFormat('sv-SE',{timeZone:'Europe/Oslo',year:'numeric',month:'2-digit'}).format(new Date(value)).slice(0,7)}
function hours(value){return Number(value||0).toLocaleString('nb-NO',{minimumFractionDigits:0,maximumFractionDigits:2})+' t'}
function renderClock(){const open=clockState?.open_entry;$('#clockStatus').textContent=open?'Du er stemplet inn':'Du er ikke stemplet inn';$('#clockDetail').textContent=open?`Siden ${formatTime(open.started_at)} · ${clockState.worksite.name}`:`${clockState.worksite.address} · ${clockState.worksite.radius_meters} meter`;$('#clockDot').classList.toggle('active',Boolean(open));$('#scanClock').textContent=open?'Skann QR-kode og stemple ut':'Skann QR-kode og stemple inn';const month=$('#periodMonth').value||localMonth(),entries=(clockState.entries||[]).filter(e=>osloMonth(e.started_at)===month),adjustments=(clockState.adjustments||[]).filter(a=>String(a.work_date).slice(0,7)===month),sick=adjustments.filter(a=>a.category==='sick_pay'),approval=(clockState.approvals||[]).find(a=>String(a.month_start).slice(0,7)===month);$('#monthTotal').textContent=hours(entries.reduce((sum,e)=>sum+durationHours(e),0)+sick.reduce((sum,a)=>sum+Number(a.hours),0));$('#overtime40').textContent=hours(adjustments.filter(a=>a.category==='overtime_40').reduce((sum,a)=>sum+Number(a.hours),0));$('#overtime100').textContent=hours(adjustments.filter(a=>a.category==='overtime_100').reduce((sum,a)=>sum+Number(a.hours),0));$('#monthState').textContent=approval?.status==='locked'?'Låst måned':approval?.status==='approved'?'Godkjent måned':'Åpen måned';$('#monthState').className=`month-state ${approval?.status||'open'}`;const rows=[...entries.map(e=>({date:String(e.started_at),html:`<div class="time-row"><span><strong>${formatDay(e.started_at)}</strong><small>${e.kind==='sick_pay'?'Sykepenger · ':''}${formatTime(e.started_at)}–${e.ended_at?formatTime(e.ended_at):'Pågår'}${e.auto_clocked_out?' · Automatisk utstemplet':''}</small></span><strong>${e.ended_at?hours(durationHours(e)):'Aktiv'}</strong></div>`})),...sick.map(a=>({date:`${a.work_date}T12:00:00Z`,html:`<div class="time-row"><span><strong>${displayDate(a.work_date)}</strong><small>Sykefravær · godkjent</small></span><strong>${hours(a.hours)}</strong></div>`}))].sort((a,b)=>b.date.localeCompare(a.date));$('#timeRows').innerHTML=rows.length?rows.map(r=>r.html).join(''):'<p class="muted">Ingen registreringer i denne måneden.</p>'}
$('#periodMonth').onchange=renderClock;

function stopScanner(){if(scannerTimer)cancelAnimationFrame(scannerTimer);scannerTimer=null;scannerStream?.getTracks().forEach(track=>track.stop());scannerStream=null;$('#scannerVideo').srcObject=null;if($('#scannerDialog').open)$('#scannerDialog').close()}
async function startScanner(){const dialog=$('#scannerDialog');dialog.showModal();$('#manualQr').classList.add('hidden');$('#scannerVideo').classList.remove('hidden');if(!('BarcodeDetector'in window)){showManualScanner('Kamera-skanning støttes ikke i denne nettleseren.');return}try{scannerStream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'}}});const video=$('#scannerVideo');video.srcObject=scannerStream;await video.play();const detector=new BarcodeDetector({formats:['qr_code']});const detect=async()=>{if(!scannerStream)return;try{const codes=await detector.detect(video);if(codes[0]?.rawValue){stopScanner();await clockWithQr(codes[0].rawValue);return}}catch{}scannerTimer=requestAnimationFrame(detect)};detect()}catch{showManualScanner('Kameraet kunne ikke åpnes. Du kan skrive inn innholdet fra QR-koden.') }}
function showManualScanner(message){$('#scannerHelp').textContent=message;$('#scannerVideo').classList.add('hidden');$('#manualQr').classList.remove('hidden')}
function getPosition(){return new Promise((resolve,reject)=>navigator.geolocation.getCurrentPosition(resolve,()=>reject(new Error('Posisjonen kunne ikke hentes. Tillat posisjonstilgang og prøv igjen.')),{enableHighAccuracy:true,timeout:15000,maximumAge:0}))}
async function clockWithQr(qrToken){const button=$('#scanClock');button.disabled=true;button.textContent='Kontrollerer posisjon …';try{const position=await getPosition();const action=clockState?.open_entry?'clock_out':'clock_in';const data=await authenticated('/functions/v1/time-clock',{method:'POST',body:{action,qr_token:qrToken,latitude:position.coords.latitude,longitude:position.coords.longitude,accuracy:position.coords.accuracy}});show(action==='clock_in'?`Stemplet inn ${formatTime(data.entry.started_at)}.`:`Stemplet ut ${formatTime(data.entry.ended_at)}.`);await loadClock()}catch(error){show(error.message)}finally{button.disabled=false;renderClock()}}
$('#scanClock').onclick=startScanner;
$('#closeScanner').onclick=stopScanner;
$('#useManualQr').onclick=async()=>{const value=$('#manualQrInput').value.trim();if(!value)return show('Skriv inn koden.');stopScanner();await clockWithQr(value)};

$('#issueQr').onclick=async()=>{if(!confirm('Lage en ny QR-kode? Den forrige koden blir ugyldig med én gang.'))return;const button=$('#issueQr');button.disabled=true;button.textContent='Lager …';try{const baseUrl=`${location.origin}${location.pathname}`;const data=await authenticated('/functions/v1/time-clock',{method:'POST',body:{action:'issue_qr',base_url:baseUrl}});const bytes=new TextEncoder().encode(data.qr_svg);let binary='';bytes.forEach(byte=>binary+=String.fromCharCode(byte));const url=`data:image/svg+xml;base64,${btoa(binary)}`;$('#qrImage').src=url;$('#downloadQr').href=url;$('#qrWorksite').textContent=data.worksite;const mode=data.location_check_required?'Posisjonskontroll er aktiv.':'Testkode: posisjonsgrensen er deaktivert.';$('#qrExpiry').textContent=`${mode} Gyldig til ${new Date(data.expires_at).toLocaleDateString('nb-NO')}. Last ned koden nå; den kan ikke hentes frem igjen.`;$('#qrResult').classList.remove('hidden');show(data.location_check_required?'Ny QR-kode er laget.':'Ny testkode er laget uten posisjonsgrense.')}catch(error){show(error.message)}finally{button.disabled=false;button.textContent='Lag ny QR-kode'}};
$('#revokeQr').onclick=async()=>{if(!confirm('Sperre gjeldende QR-kode? Ansatte kan ikke stemple med den etterpå.'))return;const button=$('#revokeQr');button.disabled=true;try{await authenticated('/functions/v1/time-clock',{method:'POST',body:{action:'revoke_qr'}});$('#qrResult').classList.add('hidden');show('QR-koden er sperret.');await loadClock()}catch(error){show(error.message)}finally{button.disabled=false}};
async function loadEmployees(){const data=await authenticated('/functions/v1/employee-admin');employees=data.employees||[];renderEmployees();const select=$('#summaryEmployee'),selected=select.value;select.innerHTML='<option value="">Alle ansatte samlet</option>'+employees.map(x=>`<option value="${x.id}">${escapeHtml(x.employee_number)} · ${escapeHtml(x.full_name)}</option>`).join('');select.value=employees.some(x=>x.id===selected)?selected:'';const approval=$('#approvalEmployee'),approvalSelected=approval.value;approval.innerHTML='<option value="">Velg ansatt</option>'+employees.map(x=>`<option value="${x.id}">${escapeHtml(x.employee_number)} · ${escapeHtml(x.full_name)}</option>`).join('');approval.value=employees.some(x=>x.id===approvalSelected)?approvalSelected:''}
function employeeWorkStatus(x){if(x.open_entry)return `<div class="work-status clocked-in"><strong>Stemplet inn · kl. ${formatTime(x.open_entry.started_at)}</strong><small>${x.open_entry.source==='manual'?'Manuelt registrert':'På jobb nå'}</small></div>`;if(x.last_entry?.ended_at)return `<div class="work-status"><strong>${x.last_entry.auto_clocked_out?'Automatisk utstemplet':'Ikke stemplet inn'}</strong><small>Sist ut · kl. ${formatTime(x.last_entry.ended_at)}</small></div>`;return '<div class="work-status"><strong>Ikke stemplet inn</strong><small>Ingen registrering</small></div>'}
function renderEmployees(){const term=$('#search').value.trim().toLowerCase();const items=employees.filter(x=>[x.employee_number,x.full_name,x.email,x.phone_number].join(' ').toLowerCase().includes(term));$('#empty').classList.toggle('hidden',items.length>0);$('#rows').innerHTML=items.map(x=>`<tr class="${x.active?'':'inactive'}"><td><div class="person"><span class="avatar">${initials(x.full_name)}</span><strong>${escapeHtml(x.full_name)}</strong></div></td><td>${escapeHtml(x.employee_number)}</td><td>${escapeHtml(x.email)}<br><small>${escapeHtml(x.phone_number||'Ingen telefon')}</small></td><td>${roleText(x.role)}</td><td>${employeeWorkStatus(x)}</td><td><span class="status ${x.active?'active':''}">${x.active?'Aktiv':'Inaktiv'}</span></td><td><div class="actions">${x.active?`<button class="secondary" data-clock="${x.id}">${x.open_entry?'Stemple ut':'Stemple inn'}</button>`:''}<button class="small" data-edit="${x.id}">Rediger</button><button class="${x.active?'danger':'secondary'}" data-toggle="${x.id}">${x.active?'Sett inaktiv':'Aktiver'}</button></div></td></tr>`).join('')}
function escapeHtml(value){const div=document.createElement('div');div.textContent=String(value);return div.innerHTML}
$('#search').oninput=renderEmployees;
$('#newEmployee').onclick=()=>{resetEmployeeForm();$('#employeeDialog').showModal()};
$('#cancel').onclick=()=>$('#employeeDialog').close();
function resetEmployeeForm(){ $('#employeeForm').reset();$('#employeeId').value='';$('#dialogTitle').textContent='Ny ansatt'}
$('#rows').onclick=event=>{const edit=event.target.closest('[data-edit]'),toggle=event.target.closest('[data-toggle]'),clock=event.target.closest('[data-clock]');if(edit){const x=employees.find(v=>v.id===edit.dataset.edit);$('#employeeId').value=x.id;$('#name').value=x.full_name;$('#number').value=x.employee_number;$('#employeeEmail').value=x.email;$('#phone').value=x.phone_number||'';$('#employeeRole').value=x.role;$('#dialogTitle').textContent='Rediger ansatt';$('#employeeDialog').showModal()}if(toggle){pendingToggle=employees.find(v=>v.id===toggle.dataset.toggle);$('#confirmTitle').textContent=pendingToggle.active?'Sett ansatt inaktiv?':'Aktiver ansatt?';$('#confirmText').textContent=pendingToggle.active?`${pendingToggle.full_name} mister tilgang til innlogging og stempling. Historikken beholdes.`:`${pendingToggle.full_name} får tilgang til innlogging og stempling igjen.`;$('#confirmAction').textContent=pendingToggle.active?'Sett inaktiv':'Aktiver';$('#confirmDialog').showModal()}if(clock){const x=employees.find(v=>v.id===clock.dataset.clock),action=x.open_entry?'clock_out':'clock_in';$('#manualClockEmployeeId').value=x.id;$('#manualClockAction').value=action;$('#manualClockReason').value='';$('#manualClockTitle').textContent=action==='clock_in'?'Stemple inn manuelt':'Stemple ut manuelt';$('#manualClockText').textContent=`${x.full_name} · ${action==='clock_in'?'innstempling':'utstempling'} registreres med tidspunktet nå.`;$('#manualClockDialog').showModal();$('#manualClockReason').focus()}};
$('#cancelManualClock').onclick=()=>$('#manualClockDialog').close();
$('#manualClockForm').onsubmit=async event=>{event.preventDefault();const button=event.submitter,clockAction=$('#manualClockAction').value;button.disabled=true;button.textContent='Registrerer …';try{await authenticated('/functions/v1/employee-admin',{method:'POST',body:{action:'manual_clock',employee_id:$('#manualClockEmployeeId').value,clock_action:clockAction,reason:$('#manualClockReason').value.trim()}});$('#manualClockDialog').close();show(clockAction==='clock_in'?'Ansatt stemplet inn manuelt.':'Ansatt stemplet ut manuelt.');await loadEmployees()}catch(error){show(error.message)}finally{button.disabled=false;button.textContent='Bekreft stempling'}};
$('#confirmDialog').addEventListener('close',async()=>{if($('#confirmDialog').returnValue!=='confirm'||!pendingToggle)return;try{await authenticated('/functions/v1/employee-admin',{method:'PATCH',body:{action:'update',id:pendingToggle.id,active:!pendingToggle.active}});show(pendingToggle.active?'Ansatt satt inaktiv':'Ansatt aktivert');await loadEmployees()}catch(error){show(error.message)}finally{pendingToggle=null}});
$('#employeeForm').onsubmit=async event=>{event.preventDefault();const id=$('#employeeId').value;const payload={action:id?'update':'create',...(id?{id}:{}),employee_number:$('#number').value.trim(),full_name:$('#name').value.trim(),email:$('#employeeEmail').value.trim().toLowerCase(),phone_number:$('#phone').value.trim(),role:$('#employeeRole').value};const button=event.submitter;button.disabled=true;try{await authenticated('/functions/v1/employee-admin',{method:id?'PATCH':'POST',body:payload});$('#employeeDialog').close();show(id?'Ansatt oppdatert':'Ansatt opprettet');await loadEmployees()}catch(error){show(error.message)}finally{button.disabled=false}};

document.querySelectorAll('.admin-tab').forEach(button=>button.onclick=()=>{document.querySelectorAll('.admin-tab').forEach(x=>x.classList.toggle('active',x===button));document.querySelectorAll('.admin-view').forEach(x=>x.classList.toggle('hidden',x.id!==button.dataset.panel));if(button.dataset.panel==='hmsAdminPanel')loadHms().catch(error=>show(error.message));if(button.dataset.panel==='sickLeaveAdminPanel')loadSickLeave(true).catch(error=>show(error.message));if(button.dataset.panel==='vacationAdminPanel')loadVacation(true).catch(error=>show(error.message));if(button.dataset.panel==='hrAdminPanel')loadHr().catch(error=>show(error.message));if(button.dataset.panel==='approvalPanel')loadMonthOverview().catch(error=>show(error.message));if(button.dataset.panel==='qrPanel')loadClock().catch(error=>show(error.message))});
function localDate(){return new Intl.DateTimeFormat('sv-SE',{timeZone:'Europe/Oslo'}).format(new Date())}
function dateTimeLocal(value){const parts=new Intl.DateTimeFormat('sv-SE',{timeZone:'Europe/Oslo',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(new Date(value)).reduce((o,p)=>(o[p.type]=p.value,o),{});return `${parts.year}-${parts.month}-${parts.day}T${parts.hour}:${parts.minute}`}
function osloWallToIso(value){const [date,time]=value.split('T'),[year,month,day]=date.split('-').map(Number),[hour,minute]=time.split(':').map(Number),wanted=Date.UTC(year,month-1,day,hour,minute);let guess=wanted;for(let i=0;i<3;i++){const p=new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Oslo',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(new Date(guess)).reduce((o,x)=>(o[x.type]=Number(x.value)||x.value,o),{});const shown=Date.UTC(p.year,p.month-1,p.day,p.hour,p.minute);guess+=wanted-shown}return new Date(guess).toISOString()}
function approvalSource(value){return({qr:'QR-kode',manual:'Manuell',automatic:'Automatisk'})[value]||value}
async function loadApproval(){const month=$('#approvalMonth').value,employeeId=$('#approvalEmployee').value;if(!month||!employeeId){show('Velg måned og ansatt.');return}const button=$('#loadApproval');button.disabled=true;button.textContent='Henter …';try{approvalData=await authenticated('/functions/v1/time-review-admin',{method:'POST',body:{action:'load',month,employee_id:employeeId}});renderApproval()}catch(error){show(error.message)}finally{button.disabled=false;button.textContent='Hent timer'}}
async function loadMonthOverview(){const month=$('#approvalMonth').value;if(!month)return;monthOverview=await authenticated('/functions/v1/time-review-admin',{method:'POST',body:{action:'overview',month}});renderMonthOverview()}
function renderMonthOverview(){const locked=monthOverview.status==='locked',rows=monthOverview.employees||[],ready=rows.length>0&&rows.every(x=>x.status==='approved'&&x.open_entries===0);$('#monthLockStatus').textContent=locked?`Låst · revisjon ${monthOverview.revision}`:ready?'Klar for låsing':'Ikke klar for låsing';$('#monthLockMessage').textContent=locked?`Låst ${new Date(monthOverview.locked_at).toLocaleString('nb-NO',{timeZone:'Europe/Oslo'})}. Rapportgrunnlaget kan ikke endres.`:rows.length?`${rows.filter(x=>x.status==='approved').length} av ${rows.length} ansatte er godkjent.`:'Ingen registreringer i denne måneden.';const button=$('#lockMonth');button.classList.toggle('hidden',locked);button.disabled=!ready;$('#monthApprovalRows').innerHTML=rows.length?`<table><thead><tr><th>Ansatt</th><th>Registreringer</th><th>Timer</th><th>Status</th><th></th></tr></thead><tbody>${rows.map(x=>`<tr><td><strong>${escapeHtml(x.employee_number)} · ${escapeHtml(x.full_name)}</strong></td><td>${x.entries}${x.open_entries?` · ${x.open_entries} åpne`:''}</td><td>${hours(x.hours)}</td><td><span class="status ${x.status==='approved'||x.status==='locked'?'active':''}">${x.status==='locked'?'Låst':x.status==='approved'?'Godkjent':'Åpen'}</span></td><td><button class="small" data-review-employee="${x.id}">Vis timer</button></td></tr>`).join('')}</tbody></table>`:'<div class="empty">Ingen registreringer i denne måneden.</div>'}
function renderApproval(){const locked=approvalData.status==='locked',approved=approvalData.status==='approved',entries=approvalData.entries||[],open=entries.some(e=>!e.ended_at);$('#approvalStatus').textContent=locked?'Låst':approved?'Godkjent':'Åpen';$('#approvalMessage').textContent=locked?'Måneden er låst og kan ikke endres.':approved?'Måneden er godkjent. En korrigering åpner godkjenningen på nytt.':open?'En åpen registrering må stemples ut før måneden kan godkjennes.':'Klar for kontroll og godkjenning.';$('#approvalHours').textContent=hours(entries.reduce((s,e)=>s+durationHours(e),0));$('#approvalEmpty').classList.toggle('hidden',entries.length>0);$('#approvalRows').innerHTML=entries.map(e=>`<tr><td>${formatDay(e.started_at)}</td><td>${formatTime(e.started_at)}</td><td>${e.ended_at?formatTime(e.ended_at):'<span class="status">Pågår</span>'}</td><td>${e.ended_at?hours(durationHours(e)):'–'}</td><td>${approvalSource(e.source)}${e.auto_clocked_out?' · automatisk ut':''}</td><td>${!locked&&e.ended_at?`<button class="small" data-time-edit="${e.id}">Rediger</button>`:''}</td></tr>`).join('');const approve=$('#approveMonth');approve.disabled=locked||open;approve.classList.toggle('hidden',locked);approve.textContent=approved?'Godkjenn på nytt':'Godkjenn måned';$('#approvalResult').classList.remove('hidden')}
$('#approvalMonth').value=localMonth();
$('#approvalMonth').onchange=()=>{$('#approvalResult').classList.add('hidden');loadMonthOverview().catch(error=>show(error.message))};
$('#loadApproval').onclick=loadApproval;
$('#monthApprovalRows').onclick=event=>{const button=event.target.closest('[data-review-employee]');if(!button)return;$('#approvalEmployee').value=button.dataset.reviewEmployee;loadApproval()};
$('#approvalRows').onclick=event=>{const button=event.target.closest('[data-time-edit]');if(!button)return;const entry=approvalData.entries.find(e=>e.id===button.dataset.timeEdit);$('#timeEditId').value=entry.id;$('#timeEditStart').value=dateTimeLocal(entry.started_at);$('#timeEditEnd').value=dateTimeLocal(entry.ended_at);$('#timeEditReason').value='';$('#timeEditDialog').showModal()};
$('#cancelTimeEdit').onclick=()=>$('#timeEditDialog').close();
$('#timeEditForm').onsubmit=async event=>{event.preventDefault();const button=event.submitter;let startedAt,endedAt;try{startedAt=osloWallToIso($('#timeEditStart').value);endedAt=osloWallToIso($('#timeEditEnd').value)}catch{return show('Kontroller tidspunktene.')}button.disabled=true;button.textContent='Lagrer …';try{await authenticated('/functions/v1/time-review-admin',{method:'POST',body:{action:'correct',month:$('#approvalMonth').value,employee_id:$('#approvalEmployee').value,entry_id:$('#timeEditId').value,started_at:startedAt,ended_at:endedAt,reason:$('#timeEditReason').value.trim()}});$('#timeEditDialog').close();show('Registreringen er korrigert og godkjenningen er åpnet på nytt.');await Promise.all([loadApproval(),loadMonthOverview()])}catch(error){show(error.message)}finally{button.disabled=false;button.textContent='Lagre korrigering'}};
$('#approveMonth').onclick=async()=>{if(!confirm('Godkjenne timene for denne ansatte og måneden?'))return;const button=$('#approveMonth');button.disabled=true;button.textContent='Godkjenner …';try{await authenticated('/functions/v1/time-review-admin',{method:'POST',body:{action:'approve',month:$('#approvalMonth').value,employee_id:$('#approvalEmployee').value}});show('Måneden er godkjent.');await Promise.all([loadApproval(),loadMonthOverview()])}catch(error){show(error.message)}finally{button.disabled=false}};
$('#lockMonth').onclick=async()=>{if(!confirm('Låse hele måneden? Etter låsing kan timene ikke endres.'))return;const button=$('#lockMonth');button.disabled=true;button.textContent='Låser …';try{const data=await authenticated('/functions/v1/time-review-admin',{method:'POST',body:{action:'lock_month',month:$('#approvalMonth').value}});show(`Måneden er låst for ${data.employees} ansatte.`);await loadMonthOverview();if($('#approvalEmployee').value)await loadApproval()}catch(error){show(error.message)}finally{button.textContent='Lås måned'}};
function currentIsoWeek(){const d=new Date(`${localDate()}T12:00:00Z`),day=d.getUTCDay()||7;d.setUTCDate(d.getUTCDate()+4-day);const yearStart=new Date(Date.UTC(d.getUTCFullYear(),0,1)),week=Math.ceil((((d-yearStart)/86400000)+1)/7);return `${d.getUTCFullYear()}-W${String(week).padStart(2,'0')}`}
function reportRange(){if($('#summaryPeriod').value==='month'){const [year,month]=$('#summaryMonth').value.split('-').map(Number),last=new Date(Date.UTC(year,month,0)).getUTCDate();return{from:`${year}-${String(month).padStart(2,'0')}-01`,to:`${year}-${String(month).padStart(2,'0')}-${last}`}}const [year,week]=$('#summaryWeek').value.split('-W').map(Number),jan4=new Date(Date.UTC(year,0,4)),monday=new Date(jan4);monday.setUTCDate(jan4.getUTCDate()-(jan4.getUTCDay()||7)+1+(week-1)*7);const sunday=new Date(monday);sunday.setUTCDate(monday.getUTCDate()+6);return{from:monday.toISOString().slice(0,10),to:sunday.toISOString().slice(0,10)}}
function reportHours(entry){return entry.ended_at?Math.max(0,(new Date(entry.ended_at)-new Date(entry.started_at))/3600000):0}
function reportRow(employee,data){const entries=data.entries.filter(e=>e.employee_id===employee.id),adjustments=data.adjustments.filter(a=>a.employee_id===employee.id);return{employee,ordinary:entries.filter(e=>e.kind==='work').reduce((s,e)=>s+reportHours(e),0),sick:entries.filter(e=>e.kind==='sick_pay').reduce((s,e)=>s+reportHours(e),0)+adjustments.filter(a=>a.category==='sick_pay').reduce((s,a)=>s+Number(a.hours),0),o40:adjustments.filter(a=>a.category==='overtime_40').reduce((s,a)=>s+Number(a.hours),0),o100:adjustments.filter(a=>a.category==='overtime_100').reduce((s,a)=>s+Number(a.hours),0),open:entries.filter(e=>!e.ended_at).length,manual:entries.filter(e=>e.source==='manual').length,entries}}
function renderSummaryReport(data){const rows=data.employees.map(e=>reportRow(e,data)),sum=key=>rows.reduce((s,r)=>s+r[key],0);$('#summaryReportTitle').textContent=`${data.from}–${data.to} · ${rows.length===1?rows[0].employee.full_name:'Alle ansatte'}`;$('#summaryReportRows').innerHTML=rows.map(r=>`<tr><td><strong>${escapeHtml(r.employee.employee_number)} · ${escapeHtml(r.employee.full_name)}</strong></td><td>${hours(r.ordinary)}</td><td>${hours(r.o40)}</td><td>${hours(r.o100)}</td><td>${hours(r.sick)}</td><td>${r.open}</td><td>${r.manual}</td></tr>`).join('');$('#summaryReportTotal').innerHTML=rows.length>1?`<tr><th>Totalt</th><th>${hours(sum('ordinary'))}</th><th>${hours(sum('o40'))}</th><th>${hours(sum('o100'))}</th><th>${hours(sum('sick'))}</th><th>${sum('open')}</th><th>${sum('manual')}</th></tr>`:'';const detail=$('#summaryDetails');if(rows.length===1){detail.classList.remove('hidden');detail.innerHTML='<h3>Registreringer dag for dag</h3>'+((rows[0].entries.length?rows[0].entries.map(e=>`<div class="time-row"><span><strong>${formatDay(e.started_at)}</strong><small>${formatTime(e.started_at)}–${e.ended_at?formatTime(e.ended_at):'Pågår'} · ${e.source==='manual'?'Manuell':'QR'}</small></span><strong>${e.ended_at?hours(reportHours(e)):'Åpen'}</strong></div>`).join(''):'<p class="muted">Ingen registreringer i perioden.</p>'))}else{detail.classList.add('hidden');detail.innerHTML=''}$('#summaryReportResult').classList.remove('hidden')}
$('#summaryWeek').value=currentIsoWeek();$('#summaryMonth').value=localMonth();
$('#summaryPeriod').onchange=()=>{$('#weekChoice').classList.toggle('hidden',$('#summaryPeriod').value!=='week');$('#monthChoice').classList.toggle('hidden',$('#summaryPeriod').value!=='month');$('#summaryReportResult').classList.add('hidden')};
$('#showSummaryReport').onclick=async()=>{const button=$('#showSummaryReport'),range=reportRange();button.disabled=true;button.textContent='Henter …';try{const data=await authenticated('/functions/v1/admin-reports',{method:'POST',body:{...range,employee_id:$('#summaryEmployee').value}});renderSummaryReport(data)}catch(error){show(error.message)}finally{button.disabled=false;button.textContent='Vis rapport'}};
$('#printSummaryReport').onclick=()=>{document.body.classList.add('print-report');window.print();setTimeout(()=>document.body.classList.remove('print-report'),500)};
const payrollCategories=[{key:'overtime_40_hours',category:'overtime_40',fallback:'Overtidstillegg 40 %'},{key:'ordinary_hours',category:'ordinary',fallback:'Timelønn'},{key:'sick_pay_hours',category:'sick_pay',fallback:'Sykepenger'},{key:'overtime_100_hours',category:'overtime_100',fallback:'Overtidstillegg 100 %'}];
function payrollSetting(row,item){const setting=row?.payroll_codes?.[item.category]||{};return{code:setting.code||'',label:setting.label||item.fallback}}
function payrollType(row,item){const setting=payrollSetting(row,item);return `${setting.code?`${setting.code} `:''}${setting.label}`}
function payrollNumber(value){return Number(value||0).toLocaleString('nb-NO',{minimumFractionDigits:2,maximumFractionDigits:2})}
function payrollPeriod(month){const [year,m]=month.split('-').map(Number),last=new Date(Date.UTC(year,m,0)).getUTCDate();return `01.${String(m).padStart(2,'0')}.${year} - ${String(last).padStart(2,'0')}.${String(m).padStart(2,'0')}.${year}`}
function payrollLines(rows){return rows.flatMap(row=>payrollCategories.filter(item=>Number(row[item.key]||0)!==0).map(item=>({employee_number:row.employee_number,employee_name:row.employee_name,type:payrollType(row,item),code:payrollSetting(row,item).code,label:payrollSetting(row,item).label,amount:Number(row[item.key]||0),category:item.category}))) }
async function loadPayrollReport(){const month=$('#payrollReportMonth').value,button=$('#loadPayrollReport');button.disabled=true;button.textContent='Henter …';try{payrollReport=await authenticated('/functions/v1/monthly-report-admin',{method:'POST',body:{action:'load',month}});renderPayrollReport()}catch(error){show(error.message)}finally{button.disabled=false;button.textContent='Hent låst rapport'}}
function renderPayrollReport(){const accountant=payrollReport.recipients.find(x=>x.recipient_type==='accountant'),admin=payrollReport.recipients.find(x=>x.recipient_type==='admin');$('#accountantEmail').value=accountant?.email||'';$('#removeAccountant').classList.toggle('hidden',!accountant);if(!payrollReport.locked){$('#payrollReportResult').classList.add('hidden');show('Måneden er ikke låst ennå.');return}const rows=payrollReport.rows||[],lines=payrollLines(rows),period=payrollPeriod(payrollReport.month),recipients=[admin?.email,accountant?.email].filter(Boolean).join(', ');$('#payrollReportTitle').textContent=`Lønnsrapport ${payrollReport.month} · revisjon ${payrollReport.lock.revision}`;$('#payrollReportPeriod').textContent=`Periode: ${period}`;$('#payrollRecipients').textContent=`Rapportmottakere: ${recipients}`;$('#payrollPrintTitle').textContent=`Lønnsrapport for perioden ${period}`;$('#payrollPrintMeta').textContent=`Låst rapport · revisjon ${payrollReport.lock.revision}`;let previous='';$('#payrollReportRows').innerHTML=lines.map(line=>{const employee=`${line.employee_number} ${line.employee_name}`,start=employee!==previous;previous=employee;return `<tr class="${start?'employee-start':''}"><td><strong>${escapeHtml(employee)}</strong></td><td>${escapeHtml(line.type)}</td><td class="numeric">${payrollNumber(line.amount)}</td></tr>`}).join('');$('#payrollReportTotal').innerHTML=payrollCategories.map(item=>{const total=rows.reduce((sum,row)=>sum+Number(row[item.key]||0),0);if(!total)return'';return `<tr><td><strong>${escapeHtml(payrollType(rows[0],item))}</strong></td><td class="numeric"><strong>${payrollNumber(total)}</strong></td></tr>`}).join('');$('#payrollReportResult').classList.remove('hidden')}
function csvCell(value){return `"${String(value??'').replaceAll('"','""')}"`}
$('#payrollReportMonth').value=localMonth();
$('#loadPayrollReport').onclick=loadPayrollReport;
$('#saveAccountant').onclick=async()=>{const email=$('#accountantEmail').value.trim(),button=$('#saveAccountant');if(!email)return show('Skriv inn regnskapsførers e-postadresse.');button.disabled=true;try{await authenticated('/functions/v1/monthly-report-admin',{method:'POST',body:{action:'save_accountant',email}});show('Rapportmottakeren er lagret.');await loadPayrollReport()}catch(error){show(error.message)}finally{button.disabled=false}};
$('#removeAccountant').onclick=async()=>{if(!confirm('Fjerne regnskapsføreren som rapportmottaker?'))return;try{await authenticated('/functions/v1/monthly-report-admin',{method:'POST',body:{action:'remove_accountant'}});$('#accountantEmail').value='';$('#removeAccountant').classList.add('hidden');show('Rapportmottakeren er fjernet.');await loadPayrollReport()}catch(error){show(error.message)}};
$('#downloadPayrollCsv').onclick=()=>{if(!payrollReport?.locked)return;const lines=[['Ansattnummer','Navn','Lønnsart-ID','Lønnsart','Antall'],...payrollLines(payrollReport.rows).map(x=>[x.employee_number,x.employee_name,x.code,x.label,payrollNumber(x.amount)])],blob=new Blob(['\ufeff'+lines.map(row=>row.map(csvCell).join(';')).join('\r\n')],{type:'text/csv;charset=utf-8'}),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=`augustum-lonnsrapport-${payrollReport.month}.csv`;link.click();URL.revokeObjectURL(url)};
$('#printPayrollReport').onclick=()=>{if(!payrollReport?.locked)return;document.body.classList.add('print-payroll');window.print();setTimeout(()=>document.body.classList.remove('print-payroll'),500)};
$('#sendPayrollReport').onclick=async()=>{if(!payrollReport?.locked)return;const recipients=payrollReport.recipients.map(x=>x.email).join(', ');if(!confirm(`Sende den låste lønnsrapporten til ${recipients}?`))return;const button=$('#sendPayrollReport');button.disabled=true;button.textContent='Sender …';try{const data=await authenticated('/functions/v1/monthly-report-admin',{method:'POST',body:{action:'send',month:payrollReport.month}});show(`Rapporten er sendt til ${data.recipients.length} mottaker(e).`)}catch(error){show(error.message)}finally{button.disabled=false;button.textContent='Send rapport'}};
$('#reportDate').value=localDate();
async function loadDailyReports(){const data=await authenticated('/functions/v1/daily-report-admin');dailyReports=data.reports||[];transportProposals=data.proposals||[];renderDailyReports()}
function renderDailyReports(){const proposalsByReport=transportProposals.reduce((map,row)=>(map[row.report_id]=(map[row.report_id]||0)+1,map),{});$('#reportsEmpty').classList.toggle('hidden',dailyReports.length>0);$('#reportRows').innerHTML=dailyReports.map(report=>`<tr><td>${escapeHtml(report.work_date)}</td><td>${report.revision}</td><td><span class="status ${report.status==='locked'?'active':''}">${report.status==='locked'?'Låst':escapeHtml(report.status)}</span></td><td>${proposalsByReport[report.id]||0}</td><td>${new Date(report.locked_at).toLocaleString('nb-NO',{timeZone:'Europe/Oslo'})}</td></tr>`).join('')}
$('#lockDailyReport').onclick=async()=>{const workDate=$('#reportDate').value,button=$('#lockDailyReport');if(!workDate)return show('Velg dato.');button.disabled=true;button.textContent='Låser …';try{const data=await authenticated('/functions/v1/daily-report-admin',{method:'POST',body:{work_date:workDate}});const count=data.report?.proposal_count||0;show(data.report?.already_locked?`Dagen er allerede låst med ${count} forslag.`:`Dagen er låst. ${count} forslag er klargjort.`);await loadDailyReports()}catch(error){show(error.message)}finally{button.disabled=false;button.textContent='Lås og klargjør forslag'}};

try{session=JSON.parse(localStorage.getItem(SESSION_KEY)||'null')}catch{saveSession(null)}
const hmsStatus=value=>({new:'Ny',in_progress:'Under behandling',closed:'Lukket'})[value]||value;
const hmsCategory=value=>({fare:'Fare',skade:'Skade',miljo:'Miljø',utstyr:'Utstyr',annet:'Annet'})[value]||value;
async function loadHms(){hmsData=await authenticated('/functions/v1/hms');renderHms()}
function hmsDocumentRows(adminView=false){const docs=hmsData.documents||[];return docs.length?docs.map(d=>`<div class="hms-row ${d.active?'':'inactive'}"><div><strong>${escapeHtml(d.title)}</strong><small>${escapeHtml(d.original_name)} · ${(d.size_bytes/1048576).toLocaleString('nb-NO',{maximumFractionDigits:1})} MB</small></div><div class="actions"><a class="small hms-link" href="${d.url}" target="_blank" rel="noopener">Åpne</a>${adminView?`<button class="secondary" data-hms-doc="${d.id}" data-active="${d.active}">${d.active?'Deaktiver':'Aktiver'}</button>`:''}</div></div>`).join(''):'<p class="muted">Ingen HMS-dokumenter er lagt inn.</p>'}
function renderHms(){if(currentEmployee?.role==='admin'){$('#adminHmsDocuments').innerHTML=hmsDocumentRows(true);$('#adminHmsDeviations').innerHTML=(hmsData.deviations||[]).length?hmsData.deviations.map(d=>`<div class="hms-deviation"><div><span class="status ${d.status==='closed'?'active':''}">${hmsStatus(d.status)}</span><strong>${escapeHtml(d.title)}</strong><small>${escapeHtml(d.employees?.employee_number||'')} · ${escapeHtml(d.employees?.full_name||'')} · ${hmsCategory(d.category)} · ${escapeHtml(d.severity)}</small><p>${escapeHtml(d.description)}</p></div><label>Status<select data-hms-status="${d.id}"><option value="new" ${d.status==='new'?'selected':''}>Ny</option><option value="in_progress" ${d.status==='in_progress'?'selected':''}>Under behandling</option><option value="closed" ${d.status==='closed'?'selected':''}>Lukket</option></select></label><label>Behandlingskommentar<textarea data-hms-comment="${d.id}" rows="2">${escapeHtml(d.admin_comment||'')}</textarea></label><button class="secondary" data-hms-save="${d.id}">Lagre behandling</button></div>`).join(''):'<p class="muted">Ingen HMS-avvik er meldt.</p>'}else{$('#employeeHmsDocuments').innerHTML=hmsDocumentRows(false);$('#employeeHmsDeviations').innerHTML=(hmsData.deviations||[]).length?hmsData.deviations.map(d=>`<div class="hms-row"><div><strong>${escapeHtml(d.title)}</strong><small>${hmsStatus(d.status)} · ${hmsCategory(d.category)} · ${new Date(d.created_at).toLocaleDateString('nb-NO')}</small>${d.admin_comment?`<p>${escapeHtml(d.admin_comment)}</p>`:''}</div></div>`).join(''):'<p class="muted">Du har ikke sendt noen avvik.</p>'}}
function fileBase64(file){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(',')[1]);reader.onerror=()=>reject(new Error('Filen kunne ikke leses.'));reader.readAsDataURL(file)})}
$('#openEmployeeHms').onclick=async()=>{try{await loadHms();$('#employeeHmsDialog').showModal()}catch(error){show(error.message)}};
$('#closeEmployeeHms').onclick=()=>$('#employeeHmsDialog').close();
$('#hmsDeviationForm').onsubmit=async event=>{event.preventDefault();const button=event.submitter;button.disabled=true;try{await authenticated('/functions/v1/hms',{method:'POST',body:{action:'submit_deviation',title:$('#hmsDeviationTitle').value.trim(),category:$('#hmsDeviationCategory').value,severity:$('#hmsDeviationSeverity').value,description:$('#hmsDeviationDescription').value.trim()}});event.target.reset();show('HMS-avviket er sendt.');await loadHms()}catch(error){show(error.message)}finally{button.disabled=false}};
$('#hmsUploadForm').onsubmit=async event=>{event.preventDefault();const file=$('#hmsDocumentFile').files[0],button=event.submitter;if(!file)return;button.disabled=true;button.textContent='Laster opp …';try{const content=await fileBase64(file);await authenticated('/functions/v1/hms',{method:'POST',body:{action:'upload_document',title:$('#hmsDocumentTitle').value.trim(),file_name:file.name,mime_type:file.type,content_base64:content}});event.target.reset();show('HMS-dokumentet er lastet opp.');await loadHms()}catch(error){show(error.message)}finally{button.disabled=false;button.textContent='Last opp dokument'}};
$('#adminHmsDocuments').onclick=async event=>{const button=event.target.closest('[data-hms-doc]');if(!button)return;try{await authenticated('/functions/v1/hms',{method:'PATCH',body:{action:'document_status',id:button.dataset.hmsDoc,active:button.dataset.active!=='true'}});await loadHms()}catch(error){show(error.message)}};
$('#adminHmsDeviations').onclick=async event=>{const button=event.target.closest('[data-hms-save]');if(!button)return;const id=button.dataset.hmsSave;button.disabled=true;try{await authenticated('/functions/v1/hms',{method:'PATCH',body:{action:'handle_deviation',id,status:document.querySelector(`[data-hms-status="${id}"]`).value,admin_comment:document.querySelector(`[data-hms-comment="${id}"]`).value.trim()}});show('Avviket er oppdatert.');await loadHms()}catch(error){show(error.message)}finally{button.disabled=false}};

const sickTypeText=value=>({self_certification:'Egenmelding',medical_certificate:'Sykmelding fra lege',sick_child:'Sykt barn'})[value]||value;
const sickStatusText=value=>({pending:'Til behandling',approved:'Godkjent',rejected:'Avvist'})[value]||value;
const displayDate=value=>new Date(`${value}T12:00:00Z`).toLocaleDateString('nb-NO');
function monthRange(){const month=localMonth(),[year,m]=month.split('-').map(Number);return{from:`${month}-01`,to:`${month}-${String(new Date(Date.UTC(year,m,0)).getUTCDate()).padStart(2,'0')}`}}
async function loadSickLeave(adminView=false){let path='/functions/v1/sick-leave';if(adminView){const from=$('#sickStatsFrom').value,to=$('#sickStatsTo').value;path+=`?from=${encodeURIComponent(from)}&to=${encodeURIComponent(to)}`}sickLeaveData=await authenticated(path);renderSickLeave()}
function sickRequestHtml(r,adminView=false){const employee=r.employees||{},period=r.start_date===r.end_date?displayDate(r.start_date):`${displayDate(r.start_date)}–${displayDate(r.end_date)}`;return `<article class="sick-request"><div class="sick-request-head"><div><strong>${adminView?`${escapeHtml(employee.employee_number||'')} · ${escapeHtml(employee.full_name||'')}`:sickTypeText(r.absence_type)}</strong><p>${adminView?sickTypeText(r.absence_type)+' · ':''}${period}</p>${r.employee_note?`<p class="muted">${escapeHtml(r.employee_note)}</p>`:''}${r.admin_comment?`<p class="muted">Kommentar: ${escapeHtml(r.admin_comment)}</p>`:''}</div><span class="status ${r.status}">${sickStatusText(r.status)}</span></div>${adminView&&r.status==='pending'?`<div class="sick-actions"><label>Kommentar<textarea data-sick-comment="${r.id}" rows="2" placeholder="Påkrevd ved avvisning"></textarea></label><button class="secondary" data-sick-handle="${r.id}" data-status="rejected">Avvis</button><button class="primary" data-sick-handle="${r.id}" data-status="approved">Godkjenn</button></div>`:''}</article>`}
function renderSickLeave(){if(currentEmployee?.role==='admin'){const stats=sickLeaveData.statistics||{};$('#sickStats').innerHTML=`<div><span>Sykefravær</span><strong>${Number(stats.absence_percentage||0).toLocaleString('nb-NO',{maximumFractionDigits:2})} %</strong></div><div><span>Godkjente timer</span><strong>${hours(stats.sick_hours)}</strong></div><div><span>Forventede timer</span><strong>${hours(stats.expected_hours)}</strong></div>`;const requests=sickLeaveData.requests||[];$('#adminSickRequests').innerHTML=requests.length?requests.map(r=>sickRequestHtml(r,true)).join(''):'<p class="muted">Ingen fraværsmeldinger i perioden.</p>'}else{const requests=sickLeaveData.requests||[];$('#employeeSickRequests').innerHTML=requests.length?requests.map(r=>sickRequestHtml(r)).join(''):'<p class="muted">Du har ikke sendt noen fraværsmeldinger.</p>'}}
function updateSickForm(){const medical=$('#sickType').value==='medical_certificate',today=localDate();$('#sickStart').max=today;$('#sickEnd').max=today;$('#sickEndLabel').classList.toggle('hidden',!medical);$('#sickEnd').required=medical;if(!medical)$('#sickEnd').value=$('#sickStart').value;$('#submitSickLeave').disabled=!$('#sickRoutineAck').checked}
$('#openSickLeave').onclick=async()=>{const today=localDate();$('#sickStart').value=today;$('#sickStart').max=today;$('#sickEnd').value=today;$('#sickEnd').max=today;$('#sickRoutineAck').checked=false;updateSickForm();try{await loadSickLeave();$('#sickLeaveDialog').showModal()}catch(error){show(error.message)}};
$('#closeSickLeave').onclick=()=>$('#sickLeaveDialog').close();
$('#sickType').onchange=updateSickForm;$('#sickStart').onchange=updateSickForm;$('#sickRoutineAck').onchange=updateSickForm;
$('#sickLeaveForm').onsubmit=async event=>{event.preventDefault();const button=event.submitter,type=$('#sickType').value,start=$('#sickStart').value,end=type==='medical_certificate'?$('#sickEnd').value:start;button.disabled=true;button.textContent='Sender …';try{const data=await authenticated('/functions/v1/sick-leave',{method:'POST',body:{action:'submit',absence_type:type,start_date:start,end_date:end,employee_note:$('#sickNote').value.trim(),routine_acknowledged:$('#sickRoutineAck').checked}});show(data.email_sent?'Sykefraværet er sendt til admin.':'Sykefraværet er registrert, men e-postvarselet kunne ikke sendes.');event.target.reset();await loadSickLeave();updateSickForm()}catch(error){show(error.message)}finally{button.textContent='Send sykefravær';updateSickForm()}};
const initialSickRange=monthRange();$('#sickStatsFrom').value=initialSickRange.from;$('#sickStatsTo').value=initialSickRange.to;
$('#loadSickStats').onclick=()=>loadSickLeave(true).catch(error=>show(error.message));
$('#adminSickRequests').onclick=async event=>{const button=event.target.closest('[data-sick-handle]');if(!button)return;const status=button.dataset.status,id=button.dataset.sickHandle,comment=document.querySelector(`[data-sick-comment="${id}"]`).value.trim();if(status==='rejected'&&comment.length<3)return show('Skriv en kort kommentar ved avvisning.');if(!confirm(status==='approved'?'Godkjenne fraværet og føre 8 timer per aktuell hverdag?':'Avvise fraværsmeldingen?'))return;button.disabled=true;try{await authenticated('/functions/v1/sick-leave',{method:'PATCH',body:{action:'handle',id,status,admin_comment:comment}});show(status==='approved'?'Fraværet er godkjent og ført i timelisten.':'Fraværet er avvist.');await loadSickLeave(true)}catch(error){show(error.message)}finally{button.disabled=false}};

const vacationTypeText=value=>({vacation:'Ferie',leave:'Permisjon'})[value]||value;
const vacationStatusText=value=>({pending:'Til behandling',approved:'Godkjent',rejected:'Avvist'})[value]||value;
const currentYear=()=>Number(localDate().slice(0,4));
function addLocalDays(value,days){const date=new Date(`${value}T12:00:00Z`);date.setUTCDate(date.getUTCDate()+days);return date.toISOString().slice(0,10)}
async function loadVacation(adminView=false){const year=adminView?Number($('#vacationAdminYear').value):currentYear();vacationData=await authenticated(`/functions/v1/vacation?year=${year}`);renderVacation(adminView)}
function vacationRequestHtml(r,adminView=false){const employee=r.employees||{},period=`${displayDate(r.start_date)}–${displayDate(r.end_date)}`;return `<article class="sick-request"><div class="sick-request-head"><div><strong>${adminView?`${escapeHtml(employee.employee_number||'')} · ${escapeHtml(employee.full_name||'')}`:vacationTypeText(r.request_type)}</strong><p>${adminView?vacationTypeText(r.request_type)+' · ':''}${period} · ${r.requested_days} ${r.requested_days===1?'dag':'dager'}</p>${r.employee_note?`<p class="muted">${escapeHtml(r.employee_note)}</p>`:''}${r.admin_comment?`<p class="muted">Kommentar: ${escapeHtml(r.admin_comment)}</p>`:''}</div><span class="status ${r.status}">${vacationStatusText(r.status)}</span></div>${adminView&&r.status==='pending'?vacationActions(r.id,'handle'):''}</article>`}
function carryoverHtml(r,adminView=false){const employee=r.employees||{};return `<article class="sick-request"><div class="sick-request-head"><div><strong>${adminView?`${escapeHtml(employee.employee_number||'')} · ${escapeHtml(employee.full_name||'')}`:'Overføring'}</strong><p>${r.days} ${r.days===1?'dag':'dager'} · ${r.from_year} → ${r.to_year}</p>${r.employee_note?`<p class="muted">${escapeHtml(r.employee_note)}</p>`:''}${r.admin_comment?`<p class="muted">Kommentar: ${escapeHtml(r.admin_comment)}</p>`:''}</div><span class="status ${r.status}">${vacationStatusText(r.status)}</span></div>${adminView&&r.status==='pending'?vacationActions(r.id,'handle_carryover'):''}</article>`}
function vacationActions(id,action){return `<div class="sick-actions"><label>Kommentar<textarea data-vacation-comment="${id}" rows="2" placeholder="Påkrevd ved avvisning"></textarea></label><button class="secondary" data-vacation-handle="${id}" data-action="${action}" data-status="rejected">Avvis</button><button class="primary" data-vacation-handle="${id}" data-action="${action}" data-status="approved">Godkjenn</button></div>`}
function renderVacation(adminView=false){if(adminView){const balances=vacationData.balances||[];$('#vacationBalances').innerHTML=balances.length?`<table><thead><tr><th>Ansatt</th><th>Tilgjengelig</th><th>Godkjent ferie</th><th>Til behandling</th><th>Overført ut</th><th>Gjenstår</th></tr></thead><tbody>${balances.map(b=>`<tr><td><strong>${escapeHtml(b.employee_number)} · ${escapeHtml(b.full_name)}</strong></td><td>${b.available}</td><td>${b.used}</td><td>${b.pending}</td><td>${b.transferred}</td><td><strong>${b.remaining}</strong></td></tr>`).join('')}</tbody></table>`:'<div class="empty">Ingen ansatte funnet.</div>';$('#adminVacationRequests').innerHTML=(vacationData.requests||[]).length?vacationData.requests.map(r=>vacationRequestHtml(r,true)).join(''):'<p class="muted">Ingen søknader dette året.</p>';$('#adminCarryoverRequests').innerHTML=(vacationData.carryovers||[]).length?vacationData.carryovers.map(r=>carryoverHtml(r,true)).join(''):'<p class="muted">Ingen overføringssøknader dette året.</p>';return}const b=vacationData.balance||{};$('#vacationBalance').innerHTML=`<div><span>Tilgjengelig ${b.year||currentYear()}</span><strong>${b.available||25} dager</strong></div><div><span>Godkjent ferie</span><strong>${b.used||0} dager</strong></div><div><span>Gjenstår</span><strong>${b.remaining??25} dager</strong></div>`;$('#employeeVacationRequests').innerHTML=(vacationData.requests||[]).length?vacationData.requests.map(r=>vacationRequestHtml(r)).join(''):'<p class="muted">Du har ingen ferie- eller permisjonssøknader.</p>';$('#employeeCarryovers').innerHTML=(vacationData.carryovers||[]).length?vacationData.carryovers.map(r=>carryoverHtml(r)).join(''):'<p class="muted">Ingen overføringssøknader.</p>'}
function setVacationDates(){const earliest=addLocalDays(localDate(),14);$('#vacationStart').min=earliest;$('#vacationEnd').min=$('#vacationStart').value||earliest;if(!$('#vacationStart').value)$('#vacationStart').value=earliest;if(!$('#vacationEnd').value||$('#vacationEnd').value<$('#vacationStart').value)$('#vacationEnd').value=$('#vacationStart').value}
$('#openVacation').onclick=async()=>{setVacationDates();$('#carryoverYear').value=currentYear();try{await loadVacation();$('#vacationDialog').showModal()}catch(error){show(error.message)}};
$('#closeVacation').onclick=()=>$('#vacationDialog').close();$('#vacationStart').onchange=setVacationDates;
$('#vacationForm').onsubmit=async event=>{event.preventDefault();const button=event.submitter;button.disabled=true;button.textContent='Sender …';try{const data=await authenticated('/functions/v1/vacation',{method:'POST',body:{action:'submit',request_type:$('#vacationType').value,start_date:$('#vacationStart').value,end_date:$('#vacationEnd').value,employee_note:$('#vacationNote').value.trim()}});show(data.email_sent?'Ønsket er sendt til admin.':'Ønsket er registrert, men e-postvarselet kunne ikke sendes.');event.target.reset();setVacationDates();await loadVacation()}catch(error){show(error.message)}finally{button.disabled=false;button.textContent='Send ønske'}};
$('#carryoverForm').onsubmit=async event=>{event.preventDefault();const button=event.submitter;button.disabled=true;try{const data=await authenticated('/functions/v1/vacation',{method:'POST',body:{action:'carryover',from_year:Number($('#carryoverYear').value),days:Number($('#carryoverDays').value),employee_note:$('#carryoverNote').value.trim()}});show(data.email_sent?'Overføringssøknaden er sendt til admin.':'Søknaden er registrert, men e-postvarselet kunne ikke sendes.');event.target.reset();$('#carryoverYear').value=currentYear();await loadVacation()}catch(error){show(error.message)}finally{button.disabled=false}};
$('#vacationAdminYear').value=currentYear();$('#loadVacationAdmin').onclick=()=>loadVacation(true).catch(error=>show(error.message));
async function handleVacationClick(event){const button=event.target.closest('[data-vacation-handle]');if(!button)return;const id=button.dataset.vacationHandle,status=button.dataset.status,action=button.dataset.action,comment=document.querySelector(`[data-vacation-comment="${id}"]`).value.trim();if(status==='rejected'&&comment.length<3)return show('Skriv en kort kommentar ved avvisning.');if(!confirm(status==='approved'?'Godkjenne søknaden?':'Avvise søknaden?'))return;button.disabled=true;try{const data=await authenticated('/functions/v1/vacation',{method:'PATCH',body:{action,id,status,admin_comment:comment}});show(data.email_sent?(status==='approved'?'Søknaden er godkjent og den ansatte er varslet.':'Søknaden er avvist og den ansatte er varslet.'):'Søknaden er behandlet, men e-posten kunne ikke sendes.');await loadVacation(true)}catch(error){show(error.message)}finally{button.disabled=false}}
$('#adminVacationRequests').onclick=handleVacationClick;$('#adminCarryoverRequests').onclick=handleVacationClick;

const hrStatusText=value=>({draft:'Utkast',locked:'Låst – klar for signering',pending_signature:'Til signering',signed:'Signert',cancelled:'Avbrutt',not_required:'Ingen signering',pending:'Venter på signering',declined:'Avvist'})[value]||value;
async function loadHr(){hrData=await authenticated('/functions/v1/hr');renderHr()}
function hrDocumentRows(adminView=false){const docs=hrData.documents||[];return docs.length?docs.map(d=>`<div class="hms-row"><div><strong>${escapeHtml(d.title)}</strong><small>${adminView?`${escapeHtml(d.employees?.employee_number||'')} · ${escapeHtml(d.employees?.full_name||'')} · `:''}${new Date(d.created_at).toLocaleDateString('nb-NO')} · ${hrStatusText(d.signature_status)}${d.read_at?' · Lest':''}</small></div><div class="actions"><a class="small hms-link" href="${d.url}" target="_blank" rel="noopener" data-hr-open="${d.id}">Åpne PDF</a></div></div>`).join(''):'<p class="muted">Ingen dokumenter er lagt inn.</p>'}
function hrContractRows(adminView=false){const contracts=hrData.contracts||[];return contracts.length?contracts.map(c=>`<article class="sick-request"><div class="sick-request-head"><div><strong>${escapeHtml(c.title)}</strong><p>${adminView?`${escapeHtml(c.employees?.employee_number||'')} · ${escapeHtml(c.employees?.full_name||'')} · `:''}Versjon ${c.version}</p></div><span class="status ${c.status}">${hrStatusText(c.status)}</span></div><details><summary>Vis kontrakt</summary><pre class="contract-preview">${escapeHtml(c.locked_content||c.content)}</pre></details>${adminView&&c.status==='draft'?`<div class="actions"><button class="secondary" data-contract-edit="${c.id}">Rediger</button><button class="primary" data-contract-lock="${c.id}">Lås kontrakt</button></div>`:''}</article>`).join(''):'<p class="muted">Ingen kontrakter er opprettet.</p>'}
function renderHr(){if(currentEmployee?.role==='admin'){const options='<option value="">Velg ansatt</option>'+hrData.employees.map(e=>`<option value="${e.id}">${escapeHtml(e.employee_number)} · ${escapeHtml(e.full_name)}</option>`).join('');$('#hrDocumentEmployee').innerHTML='<option value="all">Alle ansatte</option>'+options.slice(options.indexOf('</option>')+9);$('#hrContractEmployee').innerHTML=options;$('#adminHrDocuments').innerHTML=hrDocumentRows(true);$('#adminHrContracts').innerHTML=hrContractRows(true)}else{$('#employeeHrDocuments').innerHTML=hrDocumentRows(false);$('#employeeHrContracts').innerHTML=hrContractRows(false)}}
$('#openEmployeeHr').onclick=async()=>{try{await loadHr();$('#employeeHrDialog').showModal()}catch(error){show(error.message)}};
$('#closeEmployeeHr').onclick=()=>$('#employeeHrDialog').close();
$('#employeeHrDocuments').onclick=async event=>{const link=event.target.closest('[data-hr-open]');if(link)authenticated('/functions/v1/hr',{method:'PATCH',body:{action:'mark_read',id:link.dataset.hrOpen}}).catch(()=>{})};
$('#hrUploadForm').onsubmit=async event=>{event.preventDefault();const file=$('#hrDocumentFile').files[0],button=event.submitter;if(!file)return;button.disabled=true;button.textContent='Laster opp …';try{const data=await authenticated('/functions/v1/hr',{method:'POST',body:{action:'upload_document',title:$('#hrDocumentTitle').value.trim(),employee_id:$('#hrDocumentEmployee').value,file_name:file.name,mime_type:file.type||'application/pdf',content_base64:await fileBase64(file),requires_signature:$('#hrRequiresSignature').checked}});event.target.reset();show(`Dokumentet er lagt i arkivet til ${data.recipient_count} mottaker(e).`);await loadHr()}catch(error){show(error.message)}finally{button.disabled=false;button.textContent='Last opp og varsle'}};
function resetContractForm(){$('#hrContractForm').reset();$('#hrContractId').value='';$('#hrContractTitle').value='Arbeidsavtale';$('#hrContractEmployee').disabled=false;$('#cancelContractEdit').classList.add('hidden')}
$('#hrContractForm').onsubmit=async event=>{event.preventDefault();const id=$('#hrContractId').value,button=event.submitter;button.disabled=true;try{await authenticated('/functions/v1/hr',{method:id?'PATCH':'POST',body:{action:id?'update_contract':'create_contract',...(id?{id}:{}),employee_id:$('#hrContractEmployee').value,title:$('#hrContractTitle').value.trim(),content:$('#hrContractContent').value.trim()}});show(id?'Kontraktsutkastet er oppdatert.':'Kontraktsutkastet er opprettet.');resetContractForm();await loadHr()}catch(error){show(error.message)}finally{button.disabled=false}};
$('#cancelContractEdit').onclick=resetContractForm;
$('#adminHrContracts').onclick=async event=>{const edit=event.target.closest('[data-contract-edit]'),lock=event.target.closest('[data-contract-lock]');if(edit){const c=hrData.contracts.find(x=>x.id===edit.dataset.contractEdit);$('#hrContractId').value=c.id;$('#hrContractEmployee').value=c.employee_id;$('#hrContractEmployee').disabled=true;$('#hrContractTitle').value=c.title;$('#hrContractContent').value=c.content;$('#cancelContractEdit').classList.remove('hidden');$('#hrContractContent').focus()}if(lock){if(!confirm('Låse kontrakten? Innholdet kan ikke redigeres etterpå.'))return;lock.disabled=true;try{const data=await authenticated('/functions/v1/hr',{method:'PATCH',body:{action:'lock_contract',id:lock.dataset.contractLock}});show(data.email_sent?'Kontrakten er låst og den ansatte er varslet.':'Kontrakten er låst, men e-postvarselet kunne ikke sendes.');await loadHr()}catch(error){show(error.message)}finally{lock.disabled=false}}};

if(session?.access_token)openApp();
setInterval(()=>{if(currentEmployee?.role==='admin')loadEmployees().catch(()=>{})},60000);
